### ISSUE TITLE
AdaptiveCards still needs com.android.support:support-v4?

### ISSUE THREAD

**Issue by wongzy** [MicrosoftDocs/AdaptiveCards#427]
I try to implementation an adaptive card, but when I run our code, some errors happened, 
```
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.microsoft.editor.ux.demo, PID: 21433
    java.lang.NoClassDefFoundError: Failed resolution of: Landroid/support/v4/view/ViewCompat;
        at com.google.android.flexbox.FlexboxLayout.onLayout(FlexboxLayout.java:564)
        at android.view.View.layout(View.java:22844)
        at android.view.ViewGroup.layout(ViewGroup.java:6389)
        at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1829)
        at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1673)
        at android.widget.LinearLayout.onLayout(LinearLayout.java:1582)
        at android.view.View.layout(View.java:22844)
        at android.view.ViewGroup.layout(ViewGroup.java:6389)
        at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1829)
        at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1673)
        at android.widget.LinearLayout.onLayout(LinearLayout.java:1582)
        at android.view.View.layout(View.java:22844)
        at android.view.ViewGroup.layout(ViewGroup.java:6389)
        at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1829)
        at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1673)
        at android.widget.LinearLayout.onLayout(LinearLayout.java:1582)
        at android.view.View.layout(View.java:22844)
        at android.view.ViewGroup.layout(ViewGroup.java:6389)
        at androidx.recyclerview.widget.RecyclerView$LayoutManager.layoutDecoratedWithMargins(RecyclerView.java:9587)
        at androidx.recyclerview.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1685)
        at androidx.recyclerview.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1587)
        at androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:665)
        at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:4134)
        at androidx.recyclerview.widget.RecyclerView.dispatchLayout(RecyclerView.java:3851)
        at androidx.recyclerview.widget.RecyclerView.onLayout(RecyclerView.java:4404)
        at android.view.View.layout(View.java:22844)
        at android.view.ViewGroup.layout(ViewGroup.java:6389)
        at androidx.constraintlayout.widget.ConstraintLayout.onLayout(ConstraintLayout.java:1873)
        at android.view.View.layout(View.java:22844)
        at android.view.ViewGroup.layout(ViewGroup.java:6389)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
        at android.view.View.layout(View.java:22844)
        at android.view.ViewGroup.layout(ViewGroup.java:6389)
        at androidx.appcompat.widget.ActionBarOverlayLayout.onLayout(ActionBarOverlayLayout.java:536)
        at android.view.View.layout(View.java:22844)
        at android.view.ViewGroup.layout(ViewGroup.java:6389)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
        at android.view.View.layout(View.java:22844)
        at android.view.ViewGroup.layout(ViewGroup.java:6389)
        at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1829)
        at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1673)
        at android.widget.LinearLayout.onLayout(LinearLayout.java:1582)
        at android.view.View.layout(View.java:22844)
        at android.view.ViewGroup.layout(ViewGroup.java:6389)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
        at com.android.internal.policy.DecorView.onLayout(DecorView.java:784)
        at android.view.View.layout(View.java:22844)
        at android.view.ViewGroup.layout(ViewGroup.java:6389)
        at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:3475)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2943)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1948)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8177)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:972)
        at android.view.Choreographer.doCallbacks(Choreographer.java:796)
        at android.view.Choreographer.doFrame(Choreographer.java:731)
E/AndroidRuntime:     at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:957)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7660)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "android.support.v4.view.ViewCompat" on path: DexPathList[[dex file "/data/data/com.microsoft.editor.ux.demo/code_cache/.overlay/base.apk/classes4.dex", zip file "/data/app/~~ODD9xFZpySzWCvWRuxgyYQ==/com.microsoft.editor.ux.demo-ZZ7ANCJfJcHmiNjHV9fFvg==/base.apk"],nativeLibraryDirectories=[/data/app/~~ODD9xFZpySzWCvWRuxgyYQ==/com.microsoft.editor.ux.demo-ZZ7ANCJfJcHmiNjHV9fFvg==/lib/arm64, /data/app/~~ODD9xFZpySzWCvWRuxgyYQ==/com.microsoft.editor.ux.demo-ZZ7ANCJfJcHmiNjHV9fFvg==/base.apk!/lib/arm64-v8a, /system/lib64, /system_ext/lib64, /product/lib64]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:207)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
```
It seems io.adaptivecards:adaptivecards-android:2.8.0 needs com.google.android.flexbox.FlexboxLayout, I believe the version of flexbox is 1.0.0, and it requires android.support.v4.view.ViewCompat, but the v4 support library is incompatible with databinding.

**Comment by BabkaFox** [comment]
Still needs com.google.android.flexbox:1.0.0 https://github.com/microsoft/AdaptiveCards/blob/f095e29a013d43469cfc030a65b36116d3eec212/source/android/constants.gradle#:~:text=androidFlexboxVersion%20%3D%20%271.0.0%27

Not working for me:

    modules {
        module("com.google.android:flexbox") {
            replacedBy("com.google.android.flexbox:flexbox")
        }
    }

    implementation('io.adaptivecards:adaptivecards-android:2.8.3') {
        exclude group: "com.google.android", module: "flexbox"
    }

    implementation 'com.google.android.flexbox:flexbox:3.0.0'

Any idea?
